- name: backup current network configuration
  copy:
    src: /etc/systemd/network
    dest: /etc/systemd/network.backup/
    remote_src: true
  ignore_errors: true
  become: true

  # Pre-flight checks
- name: check existing network connectivity
  shell: |
    ping -c 1 8.8.8.8 
  register: connectivity_check
  ignore_errors: true

- name: verfiy primary interface status
  shell: |
    ip link show {{ primary_interface }} | grep "state UP"
  register: interface_check
  ignore_errors: true

- name: check for ip conflicts
  shell: |
    ip addr | grep -w "{{ bridge_ip | regex_replace('/.*$', '') }}" | grep -v "{{ bridge_name}}" || true
  register: ip_conflict
  changed_when: false

- name: Fail if IP conflict found
  fail:
    msg: "IP conflict detected for {{ bridge_ip }}"
  when: ip_conflict.sdtout != ""