- name: install packages and create script directory
  ansible.builtin.apt:
    state: present
    name:
      - build-essential
      - bat            
      - fd-find
      - fzf
      - git
      - htop
      - iotop
      - lm-sensors
      - man-db
      - manpages
      - p7zip-full
      - plocate
      - ripgrep
      - smartmontools
      - sudo
      - zsh
  become: true

- name: create script directory
  ansible.builtin.file:
    state: directory
    mode: '755'
    owner: ubuntu
    path: /home/ubuntu/scripts
  become: true