- name: install packages
  ansible.builtin.apt:
    update_cache: yes
    name:
      - build-essential
      - bat            
      - fd-find
      - fzf
      - git
      - htop
      - iotop
      - lm-sensors
      - man-db
      - manpages
      - p7zip-full
      - plocate
      - ripgrep
      - smartmontools
      - sudo
      - zsh
    state: present
  become: yes


- name: ensure plocate updatedb timer is started and enabled
  ansible.builtin.systemd:
    name: plocate-updatedb.timer
    enabled: yes
    state: started
  become: yes


- name: symlink fd to fdfind
  ansible.builtin.file:
    src: /usr/bin/fdfind
    dest: /usr/bin/fd
    state: link
  become: yes


- name: create scripts directory
  ansible.builtin.file:
    path: /home/ubuntu/scripts
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '755'
  become: yes


- name: update apt mirrors script
  ansible.builtin.copy:
    src: files/apt-select-mirror.sh
    dest: /home/ubuntu/scripts/apt-select-mirror.sh
    owner: ubuntu
    group: ubuntu
    mode: '700'
  become: yes