# install packages
- name: Install packages
  ansible.builtin.apt:
    update_cache: yes
    name:
      - lxc
      - lxc-templates
      - debootstrap
    state: present
  become: yes


# Create lxc config directory
- name: Create lxc config directory
  ansible.builtin.file:
    path: /etc/lxc
    state: directory
    owner: root
    group: root
    mode: '755'
  become: yes

# copy default conf
- name: Copy default conf
  ansible.builtin.copy:
    src: files/default.conf
    dest: /etc/lxc/default.conf
    owner: root
    group: root
    mode: '644'
  become: yes

# create backups directory -- commented out after mounting
# - name: Create backups directory
#   ansible.builtin.file:
#     path: /mnt/storage/backups/lxc
#     owner: root
#     group: root
#     mode: '700'
#     state: directory
#   become: yes


- name: .env-lxc-backups
  ansible.builtin.copy:
    src: files/.env-lxc-backups
    dest: /home/ubuntu/scripts/.env-lxc-backups
    owner: ubuntu
    group: ubuntu
    mode: '600'
  become: yes

- name: backup script for lxc zulip.local.test
  ansible.builtin.copy:
    src: files/lxc-backup-zulip-local-test.sh
    dest: /home/ubuntu/scripts/lxc-backup-zulip-local-test.sh
    owner: ubuntu
    group: ubuntu
    mode: '700'
  become: yes

- name: add backup script for lxc zulip.local.test to cron
  ansible.builtin.cron:
    name: lxc zulip.local.test backup
    minute: "11"
    hour: "1"
    user: root
    job: "/home/ubuntu/scripts/lxc-backup-zulip-local-test.sh > /dev/null 2>&1"
  become: yes

- name: ensure lxc zulip.local.test is enabled at boot
  ansible.builtin.systemd:
    name: lxc@zulip.local.test
    enabled: yes
  become: yes